#!/usr/bin/env swift

import Foundation

let sourcePath = "pets/Kuramon.json"
let destPath = "Sources/Tokengotchi/Pet/DefaultPetData.swift"

guard let data = try? Data(contentsOf: URL(fileURLWithPath: sourcePath)),
      let jsonString = String(data: data, encoding: .utf8) else {
    print("❌ Failed to read \(sourcePath)")
    exit(1)
}

let swiftCode = """
// AUTOGENERATED FILE - DO NOT EDIT
// Generated from \(sourcePath)

import Foundation

struct DefaultPetData {
    static let jsonString = #\"\"\"
\(jsonString)
\"\"\"#

}
"""

do {
    try swiftCode.write(to: URL(fileURLWithPath: destPath), atomically: true, encoding: .utf8)
    print("✅ Generated \(destPath)")
} catch {
    print("❌ Failed to write \(destPath): \(error)")
    exit(1)
}
